name: Content Validation Pipeline

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'src/content/docs/**'
      - 'scripts/**'
      - '.github/workflows/content-validation.yml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'src/content/docs/**'
      - 'scripts/**'
      - '.github/workflows/content-validation.yml'

jobs:
  validate-content:
    name: Validate Content Quality
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Validate internal links
      run: npm run validate:links
      
    - name: Validate content structure
      run: npm run validate:content
      
    - name: Generate validation report
      if: failure()
      run: |
        echo "## Content Validation Failed" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "The content validation pipeline detected issues that need to be addressed:" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### Common Issues:" >> $GITHUB_STEP_SUMMARY
        echo "- Broken internal links" >> $GITHUB_STEP_SUMMARY
        echo "- Missing frontmatter fields (title, description)" >> $GITHUB_STEP_SUMMARY
        echo "- Improper heading hierarchy" >> $GITHUB_STEP_SUMMARY
        echo "- Missing alt text for images" >> $GITHUB_STEP_SUMMARY
        echo "- SEO optimization opportunities" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "Please review the validation output above and fix the identified issues." >> $GITHUB_STEP_SUMMARY
        
    - name: Success summary
      if: success()
      run: |
        echo "## ✅ Content Validation Passed" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "All content validation checks passed successfully:" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "- ✅ Internal links are valid" >> $GITHUB_STEP_SUMMARY
        echo "- ✅ Frontmatter is properly formatted" >> $GITHUB_STEP_SUMMARY
        echo "- ✅ Content structure follows best practices" >> $GITHUB_STEP_SUMMARY
        echo "- ✅ SEO optimization is in place" >> $GITHUB_STEP_SUMMARY
        echo "- ✅ Accessibility guidelines are followed" >> $GITHUB_STEP_SUMMARY

  build-test:
    name: Test Build Process
    runs-on: ubuntu-latest
    needs: validate-content
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build site
      run: npm run build
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-output
        path: dist/
        retention-days: 7